# $Id$
# $Date$
# $Author$

# ****************************************************************************
#                   Detector Solenoid Iron Shield
# ****************************************************************************
# Made up mainly to stop flux of particles from upstream taking 
# shortcuts into the DS, and to shield the Cosmic Ray Veto
# JPM- 7feb10
########################################################################
# shift from Fe to concrete Hedin 8-2012. Use dimensions from  doc-1371
# and mechanical drawings ME-484251 and other drawings listed there. 
# dimensions differe on the order of 2 cm or less due to non-flatness of
# concrete blacks. The iron support structures on the side are included
# using the layout of the "left" side. the right side is then made
# identical to the left, which is not quite true on the back end
# use normal g4bl "CONCRETE": for now without and Fe added
# the concrete end cap comes from MD-48452
#######################################################################
param DScryo_shield_distanceX1=1550.0
param DScryo_shield_distanceX2=2050.0
param DScryo_shield_thick=$DScryo_shield_distanceX2-$DScryo_shield_distanceX1
param DScryo_shield_length=((22608+0.5*980)-(11433-0.5*430))+1000.
param DScryo_shield_z=0.5*((22608+0.5*980)+(11433-0.5*430))

if $DScryo_shield==1
# do top. note 1371 has width=4060 but that includes the width of the
# steel support. the mech drawing has the width=156.00 inches
# the length is the entire length as any gaps are filled with HTPE
# z goes from 2875 to 15749 (plus 7929 for g4bl offset 10804-23678) 
# for y. assume in g4bl that y=0 is the beam. The height of the hole at
# the backend is 115.28 inches above the floor and the height of the top
# is 215.68 inches above the floor. So the top of the concrete shield is
# 100.4 inches or y=2550.16 mm
box DS_Cryo_shield_top height=458. width=3962.4 length=12874.\
    material=CONCRETE color=$DS_Iron_Shield_color

place DS_Cryo_shield_top x=-7808 y=1809.76 z=17241.

# do sides assume that left and right are the same
# z also goes from 2875 to 15749 but the start, middle, and end are the 
#steel supports and the drawings assume a 1" space between the end of the
# concrete and the steel. This is covered up by the steel on the inside
# and ouside of the concrete.
# the height of any individual block is 39.50 inches or 1003.3 mm and so
# nominally 5 blocks are 5016.5 mm in height. But the distance in the
# drwaing on Fig 6 of doc-1371 has this as 5070 mm as this includes
# the .75" of the steel support base and that the concrete isn't perfectly
# flat. For simplicity (and that it may not matter), we'll ignore the
# base steel supports and have the concrete blocks extend from the
# top to .75" above the floor and so a height of 5070-19.1= 5050.9 
box DS_Cryo_shield_side_1 height=4226.26 width=458. length=7264.4\
    material=CONCRETE color=$DS_Iron_Shield_color

box DS_Cryo_shield_side_2 height=4226.26 width=458. length=5448.3\
    material=CONCRETE color=$DS_Iron_Shield_color
# these are the stainless steel support structures 
box DS_Cryo_shield_side_3 height=4230.76 width=508. length=19.\
    material=Fe color=$DS_Iron_Shield_color
box DS_Cryo_shield_side_4 height=4230.76 width=19. length=254.\
    material=Fe color=$DS_Iron_Shield_color
box DS_Cryo_shield_side_5 height=4230.76 width=19. length=508.\
    material=Fe color=$DS_Iron_Shield_color
# repeat except make invisible
box DS_Cryo_shield_side_1i height=4226.26 width=458. length=7264.4\
    material=CONCRETE color=$Invisible
box DS_Cryo_shield_side_2i height=4226.26 width=458. length=5448.3\
    material=CONCRETE color=$Invisible
# these are the stainless steel support structures 
box DS_Cryo_shield_side_3i height=4230.76 width=508. length=19.\
    material=Fe color=$Invisible
box DS_Cryo_shield_side_4i height=4230.76 width=19. length=254.\
    material=Fe color=$Invisible
box DS_Cryo_shield_side_5i height=4230.76 width=19. length=508.\
    material=Fe color=$Invisible

# right side x=-7808-3962.4/2+458/2= -7808 - 1752.2 = -9560.2
# highest y is bottom on top layer =y=2550.16-458=2092.16
# z goes from 2875 to 15749 (plus 7929 for g4bl offset 10804-23678)
# first is steel support
place DS_Cryo_shield_side_3 x=-9560.2 y=-534.62 z=10813.55
# next is long concrete, 1" air gap on each side, z from 2919.5-10183.9
place DS_Cryo_shield_side_1 x=-9560.2 y=-536.87 z=14480.7
# middle steel support
place DS_Cryo_shield_side_3 x=-9560.2 y=-534.62 z=18147.85
# next is short concrete, 1" air gap on each side, z from 10253.8-15702.1
place DS_Cryo_shield_side_2 x=-9560.2 y=-536.87 z=20906.95
# end steel support has extra 2.4 mm of air
place DS_Cryo_shield_side_3 x=-9560.2 y=-534.62 z=23668.45
# side walls of steel supports
place DS_Cryo_shield_side_4 x=-9823.7 y=-534.62 z=10931.
place DS_Cryo_shield_side_4 x=-9296.7 y=-534.62 z=10931.
place DS_Cryo_shield_side_4 x=-9823.7 y=-534.62 z=23551.
place DS_Cryo_shield_side_4 x=-9296.7 y=-534.62 z=23551.
place DS_Cryo_shield_side_5 x=-9823.7 y=-534.62 z=18147.85
place DS_Cryo_shield_side_5 x=-9296.7 y=-534.62 z=18147.85
# left side x= -7808 + 1752.2 = -6055.8
# first is steel support
place DS_Cryo_shield_side_3i x=-6055.8 y=-534.62 z=10813.55
# next is long concrete, 1" air gap on each side, z from 2919.5-10183.9
place DS_Cryo_shield_side_1i x=-6055.8 y=-536.87 z=14480.7
# middle steel support
place DS_Cryo_shield_side_3i x=-6055.8 y=-534.62 z=18147.85
# next is short concrete, 1" air gap on each side, z from 10253.8-15702.1
place DS_Cryo_shield_side_2i x=-6055.8 y=-536.87 z=20906.95
# end steel support has extra 2.4 mm of air
place DS_Cryo_shield_side_3i x=-6055.8 y=-534.62 z=23668.45
# side walls of steel supports
place DS_Cryo_shield_side_4i x=-6319.3 y=-534.62 z=10931.
place DS_Cryo_shield_side_4i x=-5792.3 y=-534.62 z=10931.
place DS_Cryo_shield_side_4i x=-6319.3 y=-534.62 z=23551.
place DS_Cryo_shield_side_4i x=-5792.3 y=-534.62 z=23551.
place DS_Cryo_shield_side_5i x=-6319.3 y=-534.62 z=18147.85
place DS_Cryo_shield_side_5i x=-5792.3 y=-534.62 z=18147.85

# do end cap
# z 15749 to 18049 plus 7929 23678-25978 for g4bl offset per doc-1371 
# but have Fe supports and so concrete end is at 18007+7929=25936
box DS_Cend_top height=458. width=3962.4 length=2258. \
    material=CONCRETE color=$SkyBlue
place DS_Cend_top x=-7808 y=1809.76 z=24807.
# sides. do not get steel support exactly right or complicated underneath
box DS_Cend_side_1 height=3657.6 width=457.2 length=2248.\
    material=CONCRETE color=$SkyBlue
box DS_Cend_side_3 height=3657.6 width=508. length=19.\
    material=Fe color=$SkyBlue
box DS_Cend_side_4 height=3657.6 width=19. length=254.\
    material=Fe color=$SkyBlue
box DS_Cend_side_1i height=3657.6 width=457.2 length=2248.\
    material=CONCRETE color=$Invisible
box DS_Cend_side_3i height=3657.6 width=508. length=19.\
    material=Fe color=$Invisible
box DS_Cend_side_4i height=3657.6 width=19. length=254.\
    material=Fe color=$Invisible
place DS_Cend_side_3 x=-9560.2 y=-248.04 z=23687.55
place DS_Cend_side_1 x=-9560.2 y=-248.04 z=24837.55
place DS_Cend_side_3 x=-9560.2 y=-248.04 z=25987.55
place DS_Cend_side_4 x=-9823.7 y=-248.04 z=26105.
place DS_Cend_side_4 x=-9823.7 y=-248.04 z=24964.55
# left side
place DS_Cend_side_3i x=-6055.8 y=-248.04 z=23687.55
place DS_Cend_side_1i x=-6055.8 y=-248.04 z=24837.55
place DS_Cend_side_3i x=-6055.8 y=-248.04 z=25987.55
place DS_Cend_side_4i x=-5792.3 y=-248.04 z=26105.
place DS_Cend_side_4i x=-5792.3 y=-248.04 z=24964.55

# back end - skip Fe brackets and just make solid concrete with a hole
box DS_Cend_back width=3047. height=3657.5 length=458. \
     material=CONCRETE color=$SkyBlue 

tubs DS_Cend_hole outerRadius=76.2 length=458. material=AIR color=$Red 

place DS_Cend_hole parent=DS_Cend_back y=248
place DS_Cend_back x=-7808. y=-248. z=25707.

#bottom - skip Fe brackets and just make solid concrete but 1/2" of air
# along edges
box DS_Cend_bottom width=1168.4 height=458. length=1720.85 \
     material=CONCRETE color=$SkyBlue 
box DS_Cend_bottom1 width=571.5 height=458. length=876.3 \
     material=CONCRETE color=$SkyBlue 
place DS_Cend_bottom x=-8690. y=-1847.84 z=24616.
place DS_Cend_bottom x=-6926. y=-1847.84 z=24616.
place DS_Cend_bottom1 x=-7808. y=-1847.84 z=25038.3

#old values
#box DS_Cryo_shield_a1 \
#		height=$DScryo_shield_thick \
#		width=$DScryo_shield_distanceX1 \
#		length=$DScryo_shield_length \
#		material=CONCRETE \
#		color=$DS_Iron_Shield_color
		
#box DS_Cryo_shield_b1 \
#		height=2.0*$DScryo_shield_distanceX2 \
#		width=$DScryo_shield_thick \
#		length=$DScryo_shield_length \
#		material=CONCRETE \
#		color=$DS_Iron_Shield_color

#box DS_Cryo_shield_c1 \
#		height=$DScryo_shield_thick \
#		width=$DScryo_shield_distanceX1 \
#		length=$DScryo_shield_length \
#		material=CONCRETE \
#		color=invisible
		
#box DS_Cryo_shield_d1 \
#		height=2.0*$DScryo_shield_distanceX2 \
#		width=$DScryo_shield_thick \
#		length=$DScryo_shield_length \
#		material=CONCRETE \
#		color=invisible

##********************
## 1st iron block

#place DS_Cryo_shield_a1 \
#		x=-2*$TScryo_Radius-1950-0.5*$DScryo_shield_distanceX1 \
#		y=-0.5*($DScryo_shield_distanceX1+$DScryo_shield_distanceX2) \
#		z=$DScryo_shield_z

##********************
## 3rd iron block

#place DS_Cryo_shield_a1 \
#		x=-2*$TScryo_Radius-1950-0.5*$DScryo_shield_distanceX1 \
#		y=0.5*($DScryo_shield_distanceX1+$DScryo_shield_distanceX2) \
#		z=$DScryo_shield_z

##********************
## 2nd iron block

#place DS_Cryo_shield_b1 \
#		x=-2*$TScryo_Radius-1950-0.5*($DScryo_shield_distanceX1+$DScryo_shield_distanceX2) \
#		y=0.0 \
#		z=$DScryo_shield_z

##********************
## 6st iron block (invisible)

#place DS_Cryo_shield_c1 \
#		x=-2*$TScryo_Radius-1950+0.5*$DScryo_shield_distanceX1 \
#		y=-0.5*($DScryo_shield_distanceX1+$DScryo_shield_distanceX2) \
#		z=$DScryo_shield_z

##********************
## 4rd iron block (invisible)

#place DS_Cryo_shield_c1 \
#		x=-2*$TScryo_Radius-1950+0.5*$DScryo_shield_distanceX1 \
#		y=0.5*($DScryo_shield_distanceX1+$DScryo_shield_distanceX2) \
#		z=$DScryo_shield_z

##********************
## 5nd iron block (invisible)

#place DS_Cryo_shield_d1 \
#		x=-2*$TScryo_Radius-1950+0.5*($DScryo_shield_distanceX1+$DScryo_shield_distanceX2) \
#		y=0.0 \
#		z=$DScryo_shield_z
endif
